---
abstract: 'Breaks paragraphs into lines using the TeX algorithm'
author:
  - 'Phil Perry'
build_requires:
  Class::Accessor: 0
  ExtUtils::CBuilder: 0
  Test::More: 0
  Text::Hyphen: 0
  JSON::Syck: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3623'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-KnuthPlass
provides:
  Text::KnuthPlass:
    file: lib/Text/KnuthPlass.pm
    version: 1.05
  Text::KnuthPlass::Box:
    file: lib/Text/KnuthPlass.pm
  Text::KnuthPlass::Breakpoint:
    file: lib/Text/KnuthPlass.pm
  Text::KnuthPlass::DummyHyphenator:
    file: lib/Text/KnuthPlass.pm
  Text::KnuthPlass::Element:
    file: lib/Text/KnuthPlass.pm
  Text::KnuthPlass::Glue:
    file: lib/Text/KnuthPlass.pm
  Text::KnuthPlass::Penalty:
    file: lib/Text/KnuthPlass.pm
version: 1.05
resources:
  bugtracker: https://github.com/PhilterPaper/Text-KnuthPlass/issues
  homepage: https://metacpan.org/pod/Text::KnuthPlass

