name: Test
on:
  - push
  - pull_request
jobs:
  full-ubuntu:
    name: Full_Ubuntu
    runs-on: ubuntu-latest
# disable for the time being, as can't find Module::Build
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install libmodule-build-perl
      - run: perl Build.PL
      - run: Build test TEST_VERBOSE=1
